blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from cnblog import settings


urlpatterns = [
    url(r'backend/$', views.backend),
    url(r'get_comment_tree/(\d+)$', views.get_comment_tree),
    url(r'add_article$', views.add_article),

    url(r'poll/$', views.poll),
    url(r'comment/$', views.comment),

    url(r'(?P<username>\w+)/(?P<condition>tag|cate|date)/(?P<param>.*)/', views.homesite),
    url(r'(?P<username>\w+)/articles/(?P<article_id>\d+)/', views.article_detail),
    url(r'(?P<username>\w+)/$', views.homesite),
]

cnblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog import views
from django.views.static import serve
from cnblog import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', views.login),
    url(r'^get_valid_img/', views.get_valid_img),
    url(r'^index/', views.index),
    url(r'^$', views.index),
    url(r'^reg/', views.reg),
    url(r'^blog/', include("blog.urls")),
    # media配置,对外公开
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # 文件上传
    url(r'^upload_img/', views.upload_img),
    # 删除文章
    url(r'delete_article/', views.delete_article),
    # 编辑文章
    url(r'edit_article/', views.edit_article),
    # 用户注销
    url(r'logout/', views.logout),
    # 修改用户密码
    url(r'change_password/', views.change_password),
    # 修改用户头像
    url(r'modify_avatar/', views.modify_avatar),



]

blog/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractUser


class UserInfo(AbstractUser):
    """
    用户信息表
    """
    nid = models.AutoField(primary_key=True)
    phone = models.CharField(max_length=11, null=True, unique=True)
    avatar = models.FileField(upload_to="avatars/", default="avatars/default.png", verbose_name="头像")
    create_time = models.DateTimeField(auto_now_add=True)

    blog = models.OneToOneField(to="Blog", to_field="nid", null=True)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name


class Blog(models.Model):
    """
    博客信息
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)  # 个人博客标题
    site = models.CharField(max_length=32, unique=True)  # 个人博客后缀
    theme = models.CharField(max_length=32)  # 博客主题

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog站点"
        verbose_name_plural = verbose_name


class Category(models.Model):
    """
    个人博客文章分类
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 分类标题
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 外键关联博客，一个博客站点可以有多个分类

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章分类"
        verbose_name_plural = verbose_name


class Tag(models.Model):
    """
    标签
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=32)  # 标签名
    blog = models.ForeignKey(to="Blog", to_field="nid")  # 所属博客

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = verbose_name


class Article(models.Model):
    """
    文章
    """
    nid = models.AutoField(primary_key=True)
    title = models.CharField(max_length=50, verbose_name="文章标题")  # 文章标题
    desc = models.CharField(max_length=255,verbose_name="文章描述")  # 文章描述
    create_time = models.DateTimeField(verbose_name="创建时间", auto_now_add=True)  # 创建时间

    # 评论数
    comment_count = models.IntegerField(verbose_name="评论数", default=0)
    # 点赞数
    up_count = models.IntegerField(verbose_name="点赞数", default=0)
    # 踩
    down_count = models.IntegerField(verbose_name="踩数", default=0)

    category = models.ForeignKey(to="Category", to_field="nid", null=True)
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    tags = models.ManyToManyField(  # 中介模型
        to="Tag",
        through="Article2Tag",
        through_fields=("article", "tag"),  # 注意顺序！！！
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "文章"
        verbose_name_plural = verbose_name


class ArticleDetail(models.Model):
    """
    文章详情表
    """
    nid = models.AutoField(primary_key=True)
    content = models.TextField()
    article = models.OneToOneField(to="Article", to_field="nid")

    class Meta:
        verbose_name = "文章详情"
        verbose_name_plural = verbose_name


class Article2Tag(models.Model):
    """
    文章和标签的多对多关系表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    tag = models.ForeignKey(to="Tag", to_field="nid")

    class Meta:
        unique_together = (("article", "tag"),)
        verbose_name = "文章-标签"
        verbose_name_plural = verbose_name


class ArticleUpDown(models.Model):
    """
    点赞表
    """
    nid = models.AutoField(primary_key=True)
    user = models.ForeignKey(to="UserInfo", null=True)
    article = models.ForeignKey(to="Article", null=True)
    is_up = models.BooleanField(default=True)

    class Meta:
        unique_together = (("article", "user"),)
        verbose_name = "文章点赞"
        verbose_name_plural = verbose_name


class Comment(models.Model):
    """
    评论表
    """
    nid = models.AutoField(primary_key=True)
    article = models.ForeignKey(to="Article", to_field="nid")
    user = models.ForeignKey(to="UserInfo", to_field="nid")
    content = models.CharField(max_length=255)  # 评论内容
    create_time = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey("self", null=True, blank=True)  # blank=True 在django admin里面可以不填

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name

templates/add_article.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <title>Title</title>
    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <style>
        .header{
            width: 100%;
            height: 60px;
            background-color: #9d9d9d;
        }
        .content{
            padding: 40px;
        }
    </style>
</head>
<body>
<div class="header"></div>
<div class="content">
    <form action="" method="post">
        {% csrf_token %}
        <div class="title">
            标题 <input type="text" name="title">
        </div>
        <div>
            内容:<br>
            <textarea name="article_con" id="article_box" cols="30" rows="10"></textarea>
        </div>
        <input type="submit">
    </form>
</div>
{% csrf_token %}
<script>
    KindEditor.ready(function (K) {
        window.editor=K.create("#article_box",{
            width:800,
            height:400,
            uploadJson:"/upload_img/",
            extraFileUploadParams : {
                "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val()
            }

        })
    })
</script>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <h3 class="text-center">{{ article.title }}</h3>
    <div class="content">
        {{ article.articledetail.content|safe }}
    </div>
    <div class="poll clearfix">
        <div id="div_digg">
            <div class="diggit digg">
                <span class="diggnum" id="digg_count">{{ article.up_count }}</span>
            </div>
            <div class="buryit digg">
                <span class="burynum" id="bury_count">{{ article.down_count }}</span>
            </div>
            <div class="clear"></div>
            <div class="diggword" id="digg_tips" style="color: red;"></div>
        </div>
    </div>
    <div class="info" article_id="{{ article.pk }}" username="{{ request.user.username }}"></div>

    <hr>
    <p>评论树</p>
    <div class="comment_tree"></div>
    <hr>
    <p>评论楼列表</p>
    <ul class="comment_list">
        {% for comment in comment_list %}
            <li class="list-group-item ">
                <div>
                    <a href="">#{{ forloop.counter }}楼</a> &nbsp;&nbsp;
                    <span style="color: gray">{{ comment.create_time|date:"Y-m-d H:i" }}</span> &nbsp;&nbsp;
                    <a href=""><span>{{ comment.user.username }}</span></a>
                    <a class="pull-right reply_btn" username="{{ comment.user.username }}"
                       comment_pk="{{ comment.pk }}"><span>回复</span></a>
                </div>
                {% if comment.parent_comment_id %}
                    <div class="pid_info well">
                        <p> @{{ comment.parent_comment.user.username }}:
                            &nbsp;&nbsp;&nbsp;{{ comment.parent_comment.content }} </p>
                    </div>
                {% endif %}

                <div class="con">
                    <p>
                        {{ comment.content }}
                    </p>
                </div>
            </li>
        {% endfor %}
    </ul>

    {% if request.user.username %}
        <div class="div_comment">
            <p>昵称：<input type="text" id="tbCommentAuthor" class="author" disabled="disabled" size="50"
                         value="{{ request.user.username }}"></p>
            <p>评论内容</p>
            <textarea name="" id="comment_content" cols="60" rows="10"></textarea>
            <p>
                <button id="comment_btn">提交评论</button>
            </p>

        </div>
    {% else %}
        <a href="/login/">登录</a>
    {% endif %}

    {% csrf_token %}
    <script>
    // 获取评论数据，展示评论树结构
    (function () {
        $.ajax({
            url: "/blog/get_comment_tree/{{ article_id }}",
            success: function (data) {
                console.log(data);
                $.each(data, function (index, comment_dict) {
                    var content = comment_dict.content;
                    var pk = comment_dict.pk;
                    var username = comment_dict.user__username;
                    var pid = comment_dict.parent_comment_id;
                    var s = '<div class="comment_item" comment_id=' + pk + '><span>' + username + '</span> <span class="content">' + content + '</span> </div>';
                    if (pid) {
                        // 子评论
                        $("[comment_id="+pid+"]").append(s);
                    }
                    else {//  根评论
                        $(".comment_tree").append(s);
                    }
                })

            }
        });
    })()

    </script>
    <script>
        //点赞踩灭
        $("#div_digg .digg").click(function () {
            if ("{{ request.user.username }}") {

                var is_up = $(this).hasClass("diggit");
                var article_id = "{{ article.pk }}";

                $.ajax({
                    url: "/blog/poll/",
                    type: "post",
                    data: {
                        is_up: is_up,
                        article_id: article_id,
                        csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                    },
                    success: function (data) {
                        console.log(data);
                        if (data.state) {
                            //赞或灭成功
                            if (is_up) {
                                var val = $("#digg_count").text();
                                val = parseInt(val) + 1;
                                $("#digg_count").text(val);
                            } else {
                                var val = $("#bury_count").text();
                                val = parseInt(val) + 1;
                                $("#bury_count").text(val);
                            }

                        } else {
                            //已经操作过的
                            if (data.fisrt_action) {
                                $("#digg_tips").html("您已经推荐过");
                            } else {
                                $("#digg_tips").html("您已经反对过");
                            }

                            setTimeout(function () {
                                $("#digg_tips").html("")
                            }, 1000)

                        }
                    }

                })
            } else {
                location.href = "/login"
            }
        })

        // 提交评论
        var pid = "";
        $("#comment_btn").click(function () {

            var article_id = $(".info").attr("article_id");
            var content = $("#comment_content").val();
            if (pid) {
                var index = content.indexOf("\n");
                content = content.slice(index + 1)
            }

            $.ajax({
                url: "/blog/comment/",
                type: "post",
                data: {
                    article_id: article_id,
                    content: content,
                    pid: pid,
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val(),
                },
                success: function (data) {
                    console.log(data);
                    var create_time = data.create_time;
                    var content = data.content;
                    var username = data.username;


                    var comment_li = '<li class="list-group-item"><div><span style="color: gray">' + create_time + '</span> &nbsp;&nbsp; <a href=""><span>' + username + '</span></a></div> <div class="con"> <p> ' + content + ' </p> </div> </li>';

                    $(".comment_list").append(comment_li);

                    // 清空文本框
                    $("#comment_content").val('');
                    // 清空pid
                    pid = ""
                }
            })


        });

        // 回复按钮事件
        $(".list-group-item .reply_btn").click(function () {

            $("#comment_content").focus();

            var v = "@" + $(this).attr("username") + "\n";
            $("#comment_content").val(v);


            //pid赋值
            pid = $(this).attr("comment_pk")


        })
    </script>
{% endblock %}

templates/backend.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <title>Title</title>
    <style>
        .header {
            width: 100%;
            height: 60px;
            background-color: white;
        }
        #SiteTitle {
            padding: 4px 4px 15px 80px;
        }
        #blog_title {
            font-size: 20px;
            font-weight: bold;
            float: right;
            text-align: right;
            padding: 30px 10px 10px 0;
        }
    </style>
</head>
<body>

<div class="header">
    <div id="blog_title">
        <a href="">
            {{ request.user.username }}
        </a>
    </div>
    <div id="SiteTitle">
        <a href="/index/">
            <img alt="logo" src="/static/img/adminlogo.gif">
        </a>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8 col-md-offset-2 main">
            <h1 class="page-header">
                个人管理后台
                <small>文章管理</small>
            </h1>
            <div class="panel panel-primary">
            <ul class="nav nav-sidebar">
                <li><a class="btn btn-success" href="add_article">添加文章</a></li>
            </ul>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>标题</th>
                        <th>操作</th>
                        <th>操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for i in article_list %}
                        <tr>
                            <td>{{ i.title }}</td>
                            <td>
                                <a class="btn btn-info" href="/edit_article/?id={{ i.nid }}">编辑</a>
                            </td>
                            <td>
                                <a class="btn btn-group" href="/delete_article/?id={{ i.nid }}">删除</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </div>
            <!--面板body 结束-->
        </div>
        <!--面板 结束-->

    </div>
</div>
</div>


<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/article_detail.css">
{#    <link rel="stylesheet" href="/static/css/mystyle.css">#}
    <link rel="stylesheet" href="/static/theme/{{ blog.theme }}">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        .comment_item{
            margin-left: 20px;
        }
    </style>
    <title>base</title>
    {% load my_tags %}
</head>
<body>

<div class="header">
    <p class="title">{{ blog.title }}</p>
</div>
<div class="container">
    <div class="col-md-3">
        {% get_menu username %}
    </div>
    <div class="col-md-8">
       {% block content %}
       
       {% endblock content%}
    </div>
</div>


</body>
</html>

templates/change_password.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        .container {
            margin-top: 150px;
        }
    </style>
    <title>change_password</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="">
                <div class="form-group">
                    <label for="id_user">用户名</label>
                    <input type="text" name="user" class="form-control" id="id_user" disabled="disabled" value="{{ request.user.username }}"><span class="error pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="id_pwd">原密码</label>
                    <input type="password" name="pwd" class="form-control" id="id_pwd">
                </div>
                <div class="form-group">
                    <label for="id_new_pwd">密码</label>
                    <input type="password" name="new_pwd" class="form-control" id="id_new_pwd">
                </div>
                <div class="form-group">
                    <label for="id_repeat_new_pwd">确认密码</label>
                    <input type="password" name="repeat_new_pwd" class="form-control" id="id_repeat_new_pwd"><span class="error pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="reg-btn"></label>
                    <input type="button" class="btn btn-default login_btn pull-right" id="reg-btn" value="提交"></input>
                </div>
            </form>
        </div>
    </div>
</div>
{% csrf_token %}
<script>
    //
    $("#reg-btn").click(function () {
        $.ajax({
            url: "change_password",
            type: "post",
            data: {
                "user": $("#id_user").val(),
                "pwd": $("#id_pwd").val(),
                "new_pwd": $("#id_new_pwd").val(),
                "repeat_new_pwd": $("#id_repeat_new_pwd").val(),
                "csrfmiddlewaretoken": $("[name='csrfmiddlewaretoken']").val()
            },
            success: function (data) {
                console.log(data);
                console.log(data.error_dict);
                if (data.user){
                    //修改成功
                    location.href = "/login/"
                }
                else {
                    //修改失败
                    //加载错误信息
                    $("#id_repeat_new_pwd").next().text(data.error_dict).css("color","red");
                    // 等待10秒将错误信息清空
                    setTimeout(function () {
                        $("#id_repeat_new_pwd").next().html("")
                            }, 1000)
                }
            }
        })
    });
</script>
</body>
</html>

templates/edit_article.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <title>Title</title>
    <script src="/static/kindeditor/kindeditor-all.js"></script>
    <style>
        .header{
            width: 100%;
            height: 60px;
            background-color: #9d9d9d;
        }
        .content{
            padding: 40px;
        }
    </style>
</head>
<body>
<div class="header"></div>
<div class="content">
    <form action="" method="post">
        {% csrf_token %}
        <div class="title">
            标题 <input type="text" name="title" value="{{ edit_article_obj.title }}">
        </div>
        <div>
            内容:<br>
            <textarea name="article_con" id="article_box" cols="30" rows="10">{{ edit_article_obj.articledetail.content }}</textarea>
        </div>
        <input type="submit">
    </form>
</div>
{% csrf_token %}
<script>
    KindEditor.ready(function (K) {
        window.editor=K.create("#article_box",{
            width:800,
            height:400,
            uploadJson:"/upload_img/",
            extraFileUploadParams : {
                "csrfmiddlewaretoken":$("[name='csrfmiddlewaretoken']").val()
            }

        })
    })
</script>

<script src="/static/jquery-3.2.1.min.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

templates/homesite.html
{% extends 'base.html' %}

{% block content %}
<div class="article_list">
            {% for article in article_list %}
                <div class="article_item">
                    <div><h5><a href="/blog/{{ article.user.username }}/articles/{{ article.pk }}">{{ article.title }}</a></h5></div>
                    <div class="row">

                        <div class="col-md-9 desc"><p>{{ article.desc }}</p></div>
                    </div>
                    <div class="small">
                        <span>发布于</span>&nbsp;&nbsp;&nbsp;
                        <span>{{ article.create_time|date:"Y-m-d" }}</span>&nbsp;&nbsp;&nbsp;
                        <span class="glyphicon glyphicon-comment"></span>&nbsp;评论({{ article.comment_count }})&nbsp;&nbsp;&nbsp;
                        <span class="glyphicon glyphicon-thumbs-up"></span>&nbsp;赞({{ article.up_count }})&nbsp;
                    </div>
                    <hr>
                </div>
            {% endfor %}

        </div>
{% endblock content%}

templates/menu.html
<div class="panel panel-info">
    <div class="panel-heading">我的分类</div>
    <div class="panel-body">
        {% for cate in cate_list %}
            <p><a href="/blog/{{ username }}/cate/{{ cate.0 }}/">{{ cate.0 }}({{ cate.1 }})</a></p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-danger">
    <div class="panel-heading">我的标签</div>
    <div class="panel-body">
        {% for tag in tag_list %}
            <p><a href="/blog/{{ username }}/tag/{{ tag.0 }}">{{ tag.0 }}({{ tag.1 }})</a></p>
        {% endfor %}
    </div>
</div>
<div class="panel panel-success">
    <div class="panel-heading">日期归档</div>
    <div class="panel-body">
        {% for date in date_list %}
            <p><a href="/blog/{{ username }}/date/{{ date.0 }}">{{ date.0 }}({{ date.1 }})</a></p>
        {% endfor %}
    </div>
</div>

templates/modify_avatar.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        .container {
            margin-top: 150px;
        }
        #avatar{
            display: none;
        }
        .avatar{
            width: 60px;
            height: 60px;
            margin-left: 15px;
        }
    </style>
    <title>modify_avatar</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="">
                <div class="form-group" style="display: none">
                    <label for="id_user">用户名</label>
                    <input type="text" name="user" class="form-control" id="id_user" disabled="disabled" value="{{ request.user.username }}"><span class="error pull-right"></span>
                </div>
                <div class="form-group">
                    <label for="avatar">新头像<img src="/static/img/default.png/" class="avatar" alt=""></label>
                    <input type="file" id="avatar" >
                </div>
                <div class="form-group">
                    <label for="modify_avatar"></label>
                    <input type="button" class="btn btn-default login_btn pull-right" id="modify_avatar" value="提交"></input>
                </div>
            </form>
        </div>
    </div>
</div>
{% csrf_token %}
<script>
    //图片预览
    $("#avatar").change(function () {
        var choose_file=$(this)[0].files[0];
        //创建一个文件读取的对象
        var reader = new FileReader();
        reader.readAsDataURL(choose_file);
        reader.onload = function () {
            //等上一步读完文件之后才 把图片加载到img标签中
            $(".avatar").attr("src",reader.result)
        }
    });
    //提交事件
    $("#modify_avatar").click(function () {
        var formData = new FormData();
        formData.append("user", $("#id_user").val());
        formData.append("avatar", $("#avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "modify_avatar",
            type: "post",
            processData: false,
            contentType: false,
            data: formData,
            success: function (data) {
                if (data.user){
                    //修改成功
                    location.href = "/index/"
                }
            }
        })
    });
</script>
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
    <script src="/static/jquery-3.2.1.min.js"></script>
    <script src="/static/bootstrap/js/bootstrap.min.js"></script>
    <style>
        .container {
            margin-top: 150px;
        }
        #avatar{
            display: none;
        }
        .avatar{
            width: 60px;
            height: 60px;
            margin-left: 15px;
        }
    </style>
    <title>reg</title>
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <form action="">
                {% for field in form %}
                <div class="form-group">
                    <label for>{{ field.label }}</label>
                    {{ field }}<span class="error pull-right"></span>
                </div>
                {% endfor %}

                <div class="form-group">
                    <label for="avatar">头像<img src="/static/img/default.png/" class="avatar" alt=""></label>
                    <input type="file" id="avatar" >
                </div>
                <div class="form-group">
                        <input type="button" class="btn btn-default login_btn pull-right" id="reg-btn" value="提交"></input>
                </div>

            </form>
        </div>
    </div>
</div>
{% csrf_token %}
<script>
    //图片预览
    $("#avatar").change(function () {
        // 文件对象
        var choose_file=$(this)[0].files[0];
        //创建一个文件读取的对象
        var reader = new FileReader();
        reader.readAsDataURL(choose_file);
        reader.onload = function () {
            //等上一步读完文件之后才 把图片加载到img标签中
            $(".avatar").attr("src",reader.result)
        }
    });
    //注册事件
    $("#reg-btn").click(function () {
        var formData = new FormData();
        formData.append("user", $("#id_user").val());
        formData.append("pwd", $("#id_pwd").val());
        formData.append("repeat_pwd", $("#id_repeat_pwd").val());
        formData.append("email", $("#id_email").val());
        formData.append("avatar", $("#avatar")[0].files[0]);
        formData.append("csrfmiddlewaretoken", $("[name='csrfmiddlewaretoken']").val());

        $.ajax({
            url: "",
            type: "post",
            processData: false,
            contentType: false,
            data: formData,
            success: function (data) {
                if (data.user){
                    //注册成功
                    location.href = "/login/"
                }
                else {
                    //注册失败
                    //加载错误信息
                    $.each(data.error_dict,function (field,error_list) {
                        $("#id_"+field).next().text(error_list[0]).css("color","red");
                        $("#id_"+field).parent().addClass("has-error");
                    })
                }
            }
        })
    });
    // 将所有的input框绑定获取焦点的事件，将所有的错误信息清空
    $("form input").focus(function () {
        $(this).next().text("").parent().removeClass("has-error");
    })
</script>
</body>
</html>